# Generated by Django 4.0.1 on 2022-01-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_num', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('unit_measure', models.CharField(max_length=10)),
                ('pack_type', models.CharField(max_length=100)),
            ],
        ),
    ]
