# Generated by Django 4.0.1 on 2022-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_num', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('unit_measure', models.CharField(max_length=10)),
                ('packing_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
